"""Hierarchy process-flow deck: cover + process overview (phase cards +
authority matrix) + one table slide per phase."""
from __future__ import annotations

from . import theme as T

CIRCLE = {"blue": T.BLUE, "green": T.GREEN, "amber": T.AMBER, "gold": T.GOLD}


def _cover(meta, sub, optimised):
    ver = f"v{meta.new_version}" if optimised else f"{meta.sop_id}"
    title = meta.title
    line = (f"{meta.sop_id} · v{meta.new_version} — OPTIMISED" if optimised
            else f"{meta.sop_id} · {meta.short_title.upper()}")
    return f"""
    <div class="slide"><div class="cover">
      <div class="band"></div>
      <div class="eyebrow">{T.esc(line)}</div>
      <h1>{T.esc(title)}</h1>
      <div class="sub">Hierarchy view{' · Optimised v' + meta.new_version if optimised else ''}</div>
      <div class="meta">{T.esc(sub)}</div>
      <div class="rule"></div>
      <div class="foot">Generated by Flow Agent · Powered by {T.esc(meta.catalog_short)} · 2026</div>
    </div></div>"""


def _overview(pkg, phases, n_steps, n_gateways, optimised):
    meta = pkg.meta
    cards = []
    for ph in phases:
        cards.append(f"""
        <div class="ov-card">
          <div class="ov-circle" style="background:{CIRCLE.get(ph.circle, T.BLUE)}">{T.esc(ph.pid)}</div>
          <div class="ov-name">{T.esc(ph.name)}</div>
          <div class="ov-sub">{T.esc(ph.subtitle)}</div>
          <div class="ov-summary">{T.esc(ph.summary)}</div>
          <div class="ov-roles">{T.esc(ph.roles)}</div>
        </div>""")
    auth = ""
    if pkg.authority:
        rows = "".join(
            f"<tr><td class='b'>{T.esc(a.band)}</td><td>{T.esc(a.first)}</td>"
            f"<td>{T.esc(a.second)}</td></tr>" for a in pkg.authority
        )
        auth = f"""
        <div class="kicker" style="margin:14px 0 6px">Approval / authority matrix</div>
        <table class="amx"><tbody>{rows}</tbody></table>"""
    tag = "Hierarchy · Optimised" if optimised else "Hierarchy"
    return f"""
    <div class="slide"><div class="ohead">
      <div>
        <div class="kicker">Flow Agent · Process blueprint</div>
        <h2 style="font-size:28px;color:{T.GOLD};margin-top:2px">Process overview</h2>
        <div style="color:{T.SUB};font-size:13px;margin-top:2px">
          {len(phases)} phases · {n_steps} steps · {pkg.n_roles} roles ·
          {n_gateways} decision gates</div>
      </div>
      <div class="tag">{T.esc(tag)}</div>
    </div>
    <div class="pad" style="padding-top:14px">
      <div class="kicker" style="margin-bottom:8px">Process phases</div>
      <div class="ov-row">{''.join(cards)}</div>
      {auth}
    </div></div>"""


def _kind_label(kind):
    return {"trigger": "Trigger", "process": "Process", "control": "Control",
            "handoff": "Hand-off", "complete": "Complete",
            "decision": "Decision"}.get(kind, "Process")


def _phase_slide(phase, steps, optimised):
    rows = []
    for s in steps:
        if s.kind == "decision":
            br = "<br>".join(
                f"<span class='brn'>{T.esc(b)}</span>" for b in s.branches
            )
            rows.append(f"""
            <tr class="decision">
              <td class="num">◆</td>
              <td colspan="1"><b style="color:{T.GOLD}">DECISION</b> — {T.esc(s.decision)}</td>
              <td></td>
              <td colspan="2">{br}</td>
              <td><i>{T.esc(s.controls)}</i></td>
            </tr>""")
        else:
            rows.append(f"""
            <tr>
              <td class="num">{T.esc(s.num)}<div style="font-size:9px;color:{T.GOLD3};font-weight:400">{_kind_label(s.kind)}</div></td>
              <td class="act">{T.esc(s.activity)}</td>
              <td>{T.esc(s.responsible)}</td>
              <td>{T.esc(s.output)}</td>
              <td>{T.esc(s.timeline)}</td>
              <td>{T.esc(s.controls)}</td>
            </tr>""")
    tag = "Hierarchy · Optimised" if optimised else "Hierarchy"
    return f"""
    <div class="slide"><div class="ohead">
      <div>
        <div class="kicker">Flow Agent · Process blueprint</div>
        <h2 style="font-size:26px;color:{T.GOLD};margin-top:2px">Phase {T.esc(phase.pid)} — {T.esc(phase.name)}</h2>
        <div style="color:{T.SUB};font-size:12px;margin-top:2px">{T.esc(phase.step_range)} · {T.esc(phase.subtitle)}</div>
      </div>
      <div class="tag">{T.esc(tag)}</div>
    </div>
    <div class="pad" style="padding-top:14px">
      <table class="grid">
        <thead><tr><th>#</th><th>Step / activity</th><th>Responsible</th>
        <th>Output / system</th><th>Timeline</th><th>Controls / notes</th></tr></thead>
        <tbody>{''.join(rows)}</tbody>
      </table>
    </div></div>"""


_EXTRA_CSS = f"""
<style>
.ohead {{ display:flex; align-items:center; justify-content:space-between;
          padding:14px 36px; background:{T.NAVY2}; border-bottom:1px solid {T.NAVY3}; }}
.ov-row {{ display:flex; gap:16px; }}
.ov-card {{ flex:1; background:{T.CARD}; border:1px solid {T.NAVY3};
            border-radius:12px; padding:16px; text-align:center; min-height:230px; }}
.ov-circle {{ width:64px; height:64px; border-radius:50%; margin:4px auto 12px;
              color:{T.NAVY}; font-size:26px; font-weight:700; display:flex;
              align-items:center; justify-content:center; }}
.ov-name {{ color:{T.GOLD}; font-size:17px; font-weight:700; }}
.ov-sub {{ color:{T.SUB}; font-size:12px; font-style:italic; margin-top:3px; }}
.ov-summary {{ color:{T.GOLD2}; font-size:13px; font-weight:700; margin-top:14px; }}
.ov-roles {{ color:{T.SUB}; font-size:11px; margin-top:10px; line-height:1.4; }}
table.amx {{ width:100%; border-collapse:collapse; font-size:12px; }}
table.amx td {{ background:{T.CARD}; color:{T.SUB}; padding:7px 14px;
                border-bottom:2px solid {T.NAVY}; }}
table.amx td.b {{ color:{T.GOLD}; font-weight:700; width:34%; }}
</style>"""


def render(pkg, optimised: bool = False) -> str:
    meta = pkg.meta
    phases = pkg.opt_phases if optimised else pkg.phases
    n_steps = pkg.opt_n_steps if optimised else pkg.n_steps
    n_gate = pkg.opt_n_gateways if optimised else pkg.n_gateways
    sub = pkg.hierarchy_cover_sub or "Collapsible phase breakdown with owners, timelines, and controls"
    slides = [_cover(meta, sub, optimised),
              _overview(pkg, phases, n_steps, n_gate, optimised)]
    steps = (pkg.opt_steps or pkg.steps) if optimised else pkg.steps
    steps_by_phase = {}
    for s in steps:
        steps_by_phase.setdefault(s.phase, []).append(s)
    for ph in phases:
        slides.append(_phase_slide(ph, steps_by_phase.get(ph.pid, []), optimised))
    body = _EXTRA_CSS + "".join(slides)
    return T.deck_page(body)
