"""SOP-INS-013 — Insurance Policy Administration Process (Meridian Insurance Group).

Fit-gap vs the Guidewire PolicyCenter policy-lifecycle (system-of-record) catalog.
"""
from __future__ import annotations

from generator.model import (
    Meta, Phase, Step, AuthorityRow, SwimNode, SwimEdge, SwimPhase,
    FitItem, FitPhaseBar, PhaseScoreCard, CriticalGap, ControlBar,
    Remediation, FitGap, DocSection, OptimisedDoc, SopPackage,
)

CATALOG = "Guidewire PolicyCenter — Policy Lifecycle (System-of-Record) Best-Practice Catalog"
CATALOG_SHORT = "Guidewire PolicyCenter"

meta = Meta(
    sop_id="SOP-INS-013", slug="Policy_Administration",
    title="Insurance Policy Administration", short_title="Policy administration",
    version="1.0", owner="Policy Administration — Operations",
    org="Meridian Insurance Group", catalog=CATALOG, catalog_short=CATALOG_SHORT,
    new_version="2.0", effective_date="01 October 2026",
    supersedes="v1.0 dated 01 June 2025", approved_by="Chief Operating Officer",
    classification="Internal Use Only",
)

phases = [
    Phase("1", "Application & risk assessment", "Receipt, verify, risk, price", "blue",
          "Policyholder · App Processing · Underwriting", "Steps 1–5", "5 steps + 1 gate"),
    Phase("2", "Drafting & acceptance", "Draft, approve terms, accept", "green",
          "Underwriting · Policy Admin · Policyholder", "Steps 6–9", "4 steps + 1 gate"),
    Phase("3", "Payment, issuance & in-force", "Pay, issue, dispatch, manage", "amber",
          "Finance · Policy Admin · PAS", "Steps 10–15", "6 steps"),
    Phase("4", "Claims intake & closure", "Claims intake, closure", "gold",
          "Claims · Policy Admin · Finance", "Steps 16–17", "2 steps + 1 gate"),
]

steps = [
    Step("1", "1", "Policyholder submits insurance application", "Policyholder / Agent",
         "Received via portal, agent or paper; application ID assigned; timestamp in PAS", "Day 0", "Multi-channel intake", kind="trigger"),
    Step("2", "1", "Collect and verify policyholder data", "Application Processing Staff",
         "Personal details confirmed; identity documents verified; discrepancies flagged", "Day 0–1", "Identity verification"),
    Step("3", "1", "Verify coverage details and eligibility", "Application Processing Staff",
         "Coverage type, sum insured and period reviewed against product guidelines", "Day 0–1", "Eligibility check"),
    Step("", "1", "", "", "", "", "Agent / supervisor approval", kind="decision", decision="Data & coverage verified?",
         branches=["Approved → risk assessment", "Anomaly → return to applicant (Sec 6.1)"]),
    Step("4", "1", "Conduct risk assessment based on verified data", "Underwriting Staff",
         "Risk checklist (claims history, occupation, health, credit, driving); risk score assigned", "Day 1–2", "Risk evaluation"),
    Step("5", "1", "Determine the policy price", "Underwriting Staff / Rating Engine",
         "Premium calculated on risk, coverage and rating factors; currency confirmed", "Day 2", "Rating"),
    Step("6", "2", "Draft insurance policy", "Underwriting Staff / Policy Admin",
         "Policy drafted with coverage, risk conditions, premium and terms; Legal input for non-standard clauses", "Day 2–3", "Policy drafting"),
    Step("7", "2", "Review and update policy terms and conditions", "Underwriting Staff",
         "Wording reviewed for accuracy, completeness and regulatory compliance; final terms confirmed", "Day 3", "Terms review"),
    Step("", "2", "", "", "", "", "Terms & conditions approval", kind="decision", decision="Terms approved?",
         branches=["Approved → notify policyholder", "Not approved → revise (Head of UW)"]),
    Step("8", "2", "Notify policyholder of policy terms and price", "Policy Administration Staff",
         "Formal notification (email/post): coverage, premium, schedule, start date, 10-day deadline", "Day 3", "Terms notification"),
    Step("9", "2", "Obtain policyholder consensus on terms and price", "Policy Administration Staff / Agent",
         "Acceptance via portal, signed form or recorded verbal; queries escalated", "Day 3–5", "Acceptance capture"),
    Step("10", "3", "Policyholder makes initial premium payment", "Policyholder / Finance",
         "Payment via card, banking, cheque or transfer; coverage attaches only on confirmed payment", "Day 5", "Coverage-on-payment"),
    Step("11", "3", "Formally issue the insurance policy", "Policy Administration Staff",
         "Final policy generated in PAS; policy number and effective date assigned; document linked", "Day 5", "Issuance"),
    Step("12", "3", "Dispatch policy document to policyholder", "Policy Administration Staff",
         "Schedule, certificate and PDS by email within 2 days; hard copy if required", "≤2 days", "Document SLA"),
    Step("13", "3", "Update policy information in database", "Policy Administration Staff",
         "PAS record updated and quality-checked within 1 business day of issuance", "Day +1", "Record QC"),
    Step("14", "3", "Set up policy renewal reminders", "Policy Administration Staff / PAS",
         "Automated 90/60/30-day pre-expiry alerts to policyholder and agent", "Day +1", "Renewal alerts"),
    Step("15", "3", "Monitor policyholder payment schedule", "Finance / Policy Administration",
         "Due dates tracked; reminders 7 days before due; missed payments flagged to Collections", "Ongoing", "Payment monitoring"),
    Step("16", "4", "File and manage policyholder claims", "Claims Staff / Policy Administration",
         "Claim registered in CMS; claim ID issued; routed to SOP-INS-011 or SOP-INS-012", "On claim", "Claims intake & routing"),
    Step("", "4", "", "", "", "", "Settlement approval (POL-CLAIMS-001)", kind="decision", decision="Settlement authorised?",
         branches=["Within authority → settle per claims SOP", "Above authority → Claims Manager"]),
    Step("17", "4", "Close policy at end of term or on request", "Policy Administration Staff",
         "Expiry/cancellation/breach/non-payment/ineligibility; status 'Closed'/'Lapsed'; refund per SOP-FIN-012", "≤5 days", "Closure & refund", kind="complete"),
]

authority = [
    AuthorityRow("Data & coverage approval", "Application Processing Supervisor", "Agent"),
    AuthorityRow("Underwriting decision", "Underwriting Staff", "—"),
    AuthorityRow("Policy terms approval", "Underwriting Supervisor", "Head of Underwriting"),
    AuthorityRow("Mid-term endorsement", "Policy Administration", "Underwriting"),
    AuthorityRow("Claim settlement", "Claims Adjuster / Manager", "POL-CLAIMS-001"),
    AuthorityRow("Disputed cancellation", "Compliance", "Legal"),
]

swim_phases = [
    SwimPhase("1", "Application & risk assessment", "Steps 1–5 · receipt to pricing",
        ["Policyholder / Agent", "Application Processing", "Underwriting"],
        [SwimNode("s1", "Policyholder / Agent", 0, "Submit application", "portal · agent · paper"),
         SwimNode("s2", "Application Processing", 1, "Verify data & identity", "documents checked"),
         SwimNode("s3", "Application Processing", 2, "Verify coverage eligibility", "product guidelines"),
         SwimNode("s4", "Application Processing", 3, "Data & coverage gate", "supervisor approval", kind="decision"),
         SwimNode("s5", "Underwriting", 4, "Risk assessment & pricing", "risk score · premium"),
         SwimNode("s6", "Underwriting", 3, "Discrepancy → return", "Sec 6.1", kind="exception")],
        [SwimEdge("s1", "s2", dashed=True), SwimEdge("s2", "s3"), SwimEdge("s3", "s4"),
         SwimEdge("s4", "s5", label="ok"), SwimEdge("s4", "s6", dashed=True, kind="exception", label="anom")],
        "Applications are verified for data, identity and coverage eligibility and pass an approval gate before risk assessment and pricing."),
    SwimPhase("2", "Drafting & acceptance", "Steps 6–9 · draft to acceptance",
        ["Underwriting", "Policy Admin", "Policyholder"],
        [SwimNode("a1", "Underwriting", 0, "Draft policy", "Legal for non-standard"),
         SwimNode("a2", "Underwriting", 1, "Review & terms gate", "UW supervisor approval", kind="decision"),
         SwimNode("a3", "Policy Admin", 2, "Notify policyholder", "terms · price · 10 days"),
         SwimNode("a4", "Policyholder", 3, "Accept terms", "portal / signed / verbal"),
         SwimNode("a5", "Underwriting", 2, "Dispute → revise", "max 2 offers", kind="exception")],
        [SwimEdge("a1", "a2"), SwimEdge("a2", "a3"), SwimEdge("a3", "a4"),
         SwimEdge("a3", "a5", dashed=True, kind="exception", label="dispute")],
        "Drafted policies pass a terms-approval gate before notification; disputes allow up to two revised offers before closing as not taken up."),
    SwimPhase("3", "Payment, issuance & in-force", "Steps 10–15 · pay to ongoing management",
        ["Policyholder / Finance", "Policy Admin", "PAS / Billing"],
        [SwimNode("d1", "Policyholder / Finance", 0, "Initial premium payment", "coverage on payment"),
         SwimNode("d2", "Policy Admin", 1, "Issue policy", "policy number"),
         SwimNode("d3", "Policy Admin", 2, "Dispatch documents", "schedule · cert · PDS"),
         SwimNode("d4", "PAS / Billing", 3, "Update & QC record", "≤1 day"),
         SwimNode("d5", "PAS / Billing", 4, "Renewal alerts & payment monitoring", "90/60/30-day", kind="terminal")],
        [SwimEdge("d1", "d2"), SwimEdge("d2", "d3"), SwimEdge("d3", "d4"), SwimEdge("d4", "d5")],
        "Coverage attaches on payment; the policy is issued, dispatched, quality-checked, and set up for renewal alerts and payment monitoring."),
    SwimPhase("4", "Claims intake & closure", "Steps 16–17 · lifecycle endpoints",
        ["Policyholder", "Claims", "Policy Admin / Finance"],
        [SwimNode("e1", "Policyholder", 0, "File claim", "portal · hotline"),
         SwimNode("e2", "Claims", 1, "Register & route claim", "SOP-INS-011/012"),
         SwimNode("e3", "Claims", 2, "Settlement approval gate", "POL-CLAIMS-001", kind="decision"),
         SwimNode("e4", "Policy Admin / Finance", 1, "Close policy", "expiry / request / lapse"),
         SwimNode("e5", "Policy Admin / Finance", 2, "Calculate refund & confirm", "SOP-FIN-012", kind="terminal")],
        [SwimEdge("e1", "e2"), SwimEdge("e2", "e3"), SwimEdge("e4", "e5")],
        "Claims are registered and routed to the relevant claims SOP under settlement authority; closure handles expiry, cancellation and refund."),
]

fg_items = [
    FitItem("1", "Multi-channel application intake", "FIT",
        "Portal, agent and paper intake with application ID and timestamp aligns with PolicyCenter submission intake.",
        "Application Processing", "GW-PC-SUB-01", "p1"),
    FitItem("2", "Identity & document verification", "PARTIAL",
        "Identity documents are verified, but there is no explicit sanctions/PEP screening step or continuous "
        "monitoring, only a prerequisite note — a regulatory control gap.",
        "Application Processing", "GW-PC-KYC-01", "p1"),
    FitItem("3", "Coverage eligibility check", "FIT",
        "Coverage type, sum insured and period checked against product guidelines align with PolicyCenter eligibility.",
        "Application Processing", "GW-PC-ELG-01", "p1"),
    FitItem("4", "Verification approval gate", "FIT",
        "A supervisor approval gate before risk assessment aligns with PolicyCenter submission governance.",
        "Application Processing Supervisor", "GW-PC-GAT-01", "p1"),
    FitItem("5", "Risk assessment & rating", "PARTIAL",
        "A manual risk checklist plus rating engine is used; PolicyCenter recommends automated underwriting with a "
        "predictive risk model to widen straight-through processing.",
        "Underwriting / Rating Engine", "GW-PC-UW-02", "p1"),
    FitItem("6", "Policy drafting & clause library", "PARTIAL",
        "Policies are drafted with Legal input for non-standard clauses; PolicyCenter generates documents from a "
        "configurable product/clause library, reducing manual drafting and error.",
        "Underwriting / Policy Admin", "GW-PC-DOC-02", "p2"),
    FitItem("7", "Terms review & approval gate", "FIT",
        "Regulatory-compliance review with a terms-approval gate aligns with PolicyCenter terms governance.",
        "Underwriting Supervisor", "GW-PC-GAT-02", "p2"),
    FitItem("8", "Terms notification", "FIT",
        "Formal multi-channel notification with a response deadline aligns with PolicyCenter offer communication.",
        "Policy Administration", "GW-PC-OFR-01", "p2"),
    FitItem("9", "Acceptance & e-signature", "GAP",
        "Acceptance may be verbal; DocuSign exists but is not mandated. PolicyCenter requires an auditable "
        "e-signature acceptance of terms before issuance — a conduct and evidencing gap.",
        "Policy Administration / Agent", "GW-PC-ISS-04", "p2"),
    FitItem("10", "Payment & coverage attachment", "FIT",
        "Coverage attaching only on confirmed payment aligns with PolicyCenter bind-on-payment control.",
        "Finance", "GW-PC-BIL-02", "p3"),
    FitItem("11", "Issuance & document dispatch", "FIT",
        "Issuance with policy number, effective date and 2-day document dispatch aligns with PolicyCenter issuance.",
        "Policy Administration", "GW-PC-ISS-01", "p3"),
    FitItem("12", "Record quality & data integrity", "PARTIAL",
        "Records are quality-checked manually within a day; PolicyCenter validates data integrity automatically as "
        "the system of record, reducing downstream errors.",
        "Policy Administration", "GW-PC-DQ-01", "p3"),
    FitItem("13", "Renewal & payment monitoring", "FIT",
        "Automated renewal alerts and payment-schedule monitoring align with PolicyCenter lifecycle management.",
        "Policy Administration / Finance", "GW-PC-REN-01", "p3"),
    FitItem("14", "Mid-term endorsements", "GAP",
        "Mid-term changes are assessed manually with a 5-day endorsement SLA. PolicyCenter supports self-service and "
        "straight-through endorsements for standard changes — a service and efficiency gap.",
        "Policy Administration / Underwriting", "GW-PC-END-01", "p3"),
    FitItem("15", "Claims intake & routing", "FIT",
        "Claim registration, ID issue and routing to the relevant claims SOP align with PolicyCenter-to-claims handoff.",
        "Claims Staff", "GW-PC-CLM-01", "p4"),
    FitItem("16", "Policy closure & refund", "FIT",
        "Closure for expiry/cancellation/lapse with unearned-premium refund aligns with PolicyCenter cancellation.",
        "Policy Administration", "GW-PC-CAN-01", "p4"),
]

fitgap = FitGap(
    overall_fit=67, partial_pct=20, fits=10, gaps=2, partials=4,
    steps_analysed=16, phases_count=4,
    summary_line="Overall alignment of SOP-INS-013 against the Guidewire PolicyCenter lifecycle catalog",
    metrics=[
        ("Steps analysed", "16 steps across 4 phases"),
        ("Fits confirmed", "10 steps aligned to catalog"),
        ("Gaps identified", "2 steps — remediation required"),
        ("Partial fits", "4 steps — enhancement recommended"),
        ("Highest risk area", "No explicit KYC/sanctions step"),
        ("Conduct gap", "E-signature not mandated"),
        ("Ref standard", "Guidewire PolicyCenter Lifecycle Catalog"),
    ],
    phase_bars=[
        FitPhaseBar("Phase 1", "Application", 68, ""),
        FitPhaseBar("Phase 2", "Drafting", 64, ""),
        FitPhaseBar("Phase 3", "In-force", 72, ""),
        FitPhaseBar("Phase 4", "Claims/close", 80, ""),
    ],
    phase_cards=[
        PhaseScoreCard("Phase 1", 68, "Application & risk"),
        PhaseScoreCard("Phase 2", 64, "Drafting & acceptance"),
        PhaseScoreCard("Phase 3", 72, "Payment & in-force"),
        PhaseScoreCard("Phase 4", 80, "Claims & closure"),
    ],
    detail_slides=[
        ("Phase 1 — Application & risk assessment", "Steps 1–5 vs Guidewire PolicyCenter lifecycle catalog", ["p1"]),
        ("Phase 2 — Drafting & acceptance", "Steps 6–9 vs Guidewire PolicyCenter lifecycle catalog", ["p2"]),
        ("Phase 3 — Payment, issuance & in-force", "Steps 10–14 vs Guidewire PolicyCenter lifecycle catalog", ["p3"]),
        ("Phase 4 — Claims intake & closure", "Steps 15–16 vs Guidewire PolicyCenter lifecycle catalog", ["p4"]),
    ],
    items=fg_items,
    groups=[("p1", "PHASE 1 — APPLICATION & RISK ASSESSMENT"),
            ("p2", "PHASE 2 — DRAFTING & ACCEPTANCE"),
            ("p3", "PHASE 3 — PAYMENT, ISSUANCE & IN-FORCE"),
            ("p4", "PHASE 4 — CLAIMS INTAKE & CLOSURE")],
    critical_missing=[
        CriticalGap("KYC / sanctions screening & monitoring",
            "Identity documents are verified but there is no explicit sanctions/PEP screening step or continuous "
            "monitoring across the lifecycle — a regulatory control gap versus the catalog."),
        CriticalGap("Mandatory e-signature acceptance",
            "Acceptance may be verbal and DocuSign is not mandated; the catalog requires an auditable e-signature "
            "acceptance of terms before issuance, a conduct and evidencing gap."),
        CriticalGap("Automated underwriting & document generation",
            "Risk assessment and policy drafting are largely manual; the catalog uses automated underwriting with a "
            "predictive model and a configurable clause library to widen STP and cut error."),
        CriticalGap("Self-service & straight-through endorsements",
            "Mid-term changes are assessed manually; the catalog supports self-service and straight-through "
            "endorsements for standard changes, improving service and efficiency."),
    ],
    radar=[("Intake", 78), ("KYC / sanctions", 42), ("Underwriting", 60), ("Acceptance", 55),
           ("Issuance", 80), ("Endorsements", 48), ("Closure", 82)],
    control_bars=[
        ControlBar("Application intake", 78, "Multi-channel with ID verification"),
        ControlBar("KYC / sanctions", 42, "No explicit screening or monitoring step"),
        ControlBar("Automated underwriting", 60, "Manual checklist; rating engine only"),
        ControlBar("Acceptance & e-signature", 55, "Verbal allowed; DocuSign not mandated"),
        ControlBar("Issuance & dispatch", 80, "Bind-on-payment with 2-day documents"),
        ControlBar("Endorsements", 48, "Manual mid-term changes; no self-service"),
        ControlBar("Closure & refund", 82, "Closure with unearned-premium refund"),
    ],
    remediations=[
        Remediation(1, "Add KYC / sanctions screening & continuous monitoring",
            "Insert an explicit identity/sanctions screening step at application and continuous watchlist monitoring "
            "across the lifecycle; route hits to Compliance. Effort: 4 weeks.", "High"),
        Remediation(2, "Mandate e-signature acceptance",
            "Require auditable DocuSign acceptance of terms before issuance, replacing verbal confirmation. "
            "Effort: 3 weeks.", "High"),
        Remediation(3, "Introduce automated underwriting & clause-library generation",
            "Add automated underwriting with a predictive risk model and generate policy documents from a "
            "configurable product/clause library. Effort: 8 weeks.", "High"),
        Remediation(4, "Enable self-service & straight-through endorsements",
            "Allow standard mid-term changes to be self-served and processed straight-through, routing only complex "
            "endorsements to underwriting. Effort: 6 weeks.", "Medium"),
        Remediation(5, "Automate data-quality validation",
            "Validate policy data integrity automatically at issuance rather than manual QC, reducing downstream "
            "errors. Effort: 3 weeks.", "Medium"),
    ],
    risk_impact=[("KYC / sanctions", 88), ("E-signature", 75), ("Automated underwriting", 70),
                 ("Self-service endorsements", 60), ("Data-quality automation", 52), ("Clause library", 55)],
    projected_fit=90,
)

opt_phases = [
    Phase("1", "Application, screening & risk", "Verify, KYC, automated UW", "blue",
          "Policyholder · App Processing · Underwriting", "Steps 1–6", "6 steps + 1 gate"),
    Phase("2", "Drafting & e-acceptance", "Generate, approve, e-sign", "green",
          "Underwriting · Policy Admin · Policyholder", "Steps 7–10", "4 steps + 1 gate"),
    Phase("3", "Payment, issuance & in-force", "Pay, issue, validate, self-service", "amber",
          "Finance · Policy Admin · PAS", "Steps 11–16", "6 steps"),
    Phase("4", "Claims intake & closure", "Claims intake, closure", "gold",
          "Claims · Policy Admin · Finance", "Steps 17–18", "2 steps + 1 gate"),
]

opt_steps = [
    Step("1", "1", "Policyholder submits insurance application", "Policyholder / Agent",
         "Received via portal, agent or paper; application ID; timestamp", "Day 0", "Standard", kind="trigger"),
    Step("2", "1", "Collect and verify policyholder data", "Application Processing Staff",
         "Personal details confirmed; identity documents verified", "Day 0–1", "Standard"),
    Step("3", "1", "KYC / sanctions screening", "Application Processing / Compliance",
         "Identity proofed; sanctions/PEP screened; continuous monitoring enabled", "Day 0–1",
         "NEW (v2.0) — regulatory control"),
    Step("4", "1", "Verify coverage details and eligibility", "Application Processing Staff",
         "Coverage type, sum insured and period checked against guidelines", "Day 0–1", "Standard"),
    Step("", "1", "", "", "", "", "Verification gate", kind="decision", decision="Verified & screened?",
         branches=["Approved → underwriting", "Anomaly/hit → return / Compliance (Sec 6.1)"]),
    Step("5", "1", "Automated underwriting with predictive model", "Underwriting / Model Engine",
         "Risk scored by predictive model; rules-clear cases straight-through; refer otherwise", "Day 1",
         "ENHANCED (v2.0) — STP underwriting"),
    Step("6", "1", "Determine the policy price", "Underwriting / Rating Engine",
         "Premium calculated on risk, coverage and rating factors; currency confirmed", "Day 1–2", "Standard"),
    Step("7", "2", "Generate policy from clause library", "Underwriting / Policy Admin",
         "Policy documents generated from a configurable product/clause library; Legal for exceptions", "Day 2",
         "ENHANCED (v2.0) — document automation"),
    Step("8", "2", "Review and confirm terms", "Underwriting Staff",
         "Wording reviewed for accuracy and regulatory compliance; final terms confirmed", "Day 2", "Standard"),
    Step("", "2", "", "", "", "", "Terms approval", kind="decision", decision="Terms approved?",
         branches=["Approved → notify", "Not approved → revise (Head of UW)"]),
    Step("9", "2", "Notify policyholder of terms and price", "Policy Administration Staff",
         "Coverage, premium, schedule, start date and 10-day deadline notified", "Day 2", "Standard"),
    Step("10", "2", "Obtain acceptance via mandatory e-signature", "Policyholder / Policy Admin",
         "Auditable DocuSign acceptance of terms captured before issuance", "Day 2–4",
         "NEW (v2.0) — conduct control"),
    Step("11", "3", "Initial premium payment", "Policyholder / Finance",
         "Payment via card, banking, cheque or transfer; coverage attaches on confirmed payment", "Day 4", "Standard"),
    Step("12", "3", "Formally issue the insurance policy", "Policy Administration Staff",
         "Policy generated in PAS; number and effective date assigned; document linked", "Day 4", "Standard"),
    Step("13", "3", "Dispatch policy document to policyholder", "Policy Administration Staff",
         "Schedule, certificate and PDS by email within 2 days; hard copy if required", "≤2 days", "Standard"),
    Step("14", "3", "Automated data-quality validation", "PAS / System",
         "Policy data integrity validated automatically at issuance", "Day +0", "NEW (v2.0) — data integrity"),
    Step("15", "3", "Renewal reminders & payment monitoring", "Policy Administration / PAS",
         "Automated 90/60/30-day alerts; payment schedule monitored; missed payments flagged", "Ongoing", "Standard"),
    Step("16", "3", "Self-service & straight-through endorsements", "Policyholder / Policy Admin",
         "Standard mid-term changes self-served and processed straight-through; complex routed to UW", "On request",
         "NEW (v2.0) — service & efficiency"),
    Step("17", "4", "File and manage policyholder claims", "Claims Staff / Policy Administration",
         "Claim registered in CMS; routed to SOP-INS-011 or SOP-INS-012", "On claim", "Standard"),
    Step("", "4", "", "", "", "", "Settlement approval (POL-CLAIMS-001)", kind="decision", decision="Settlement authorised?",
         branches=["Within authority → settle", "Above authority → Claims Manager"]),
    Step("18", "4", "Close policy at end of term or on request", "Policy Administration Staff",
         "Status 'Closed'/'Lapsed'; unearned-premium refund per SOP-FIN-012", "≤5 days", "Standard", kind="complete"),
]

opt_swim_phases = [
    SwimPhase("1", "Application, screening & risk", "Steps 1–6 · v2.0 adds KYC & automated UW",
        ["Policyholder / Agent", "App Processing / Compliance", "Underwriting / Model"],
        [SwimNode("o1", "Policyholder / Agent", 0, "Submit application", "portal · agent · paper"),
         SwimNode("o2", "App Processing / Compliance", 1, "Verify data & identity", "documents checked"),
         SwimNode("o3", "App Processing / Compliance", 2, "KYC / sanctions screening", "watchlists", kind="new"),
         SwimNode("o4", "App Processing / Compliance", 3, "Verification gate", "approval", kind="decision"),
         SwimNode("o5", "Underwriting / Model", 4, "Automated underwriting", "predictive score", kind="enhanced")],
        [SwimEdge("o1", "o2", dashed=True), SwimEdge("o2", "o3", dashed=True, kind="new", label="KYC"),
         SwimEdge("o3", "o4"), SwimEdge("o4", "o5", label="ok")],
        "v2.0 adds an explicit KYC/sanctions screening step and automated, model-scored underwriting before pricing."),
    SwimPhase("2", "Drafting & e-acceptance", "Steps 7–10 · clause library & e-signature",
        ["Underwriting", "Policy Admin", "Policyholder"],
        [SwimNode("p1", "Underwriting", 0, "Generate from clause library", "configurable templates", kind="enhanced"),
         SwimNode("p2", "Underwriting", 1, "Review & terms gate", "approval", kind="decision"),
         SwimNode("p3", "Policy Admin", 2, "Notify policyholder", "terms · price · 10 days"),
         SwimNode("p4", "Policyholder", 3, "Accept via e-signature", "DocuSign", kind="new")],
        [SwimEdge("p1", "p2"), SwimEdge("p2", "p3"), SwimEdge("p3", "p4", dashed=True, kind="new", label="e-sign")],
        "v2.0 generates policy documents from a clause library and mandates an auditable e-signature acceptance before issuance."),
    SwimPhase("3", "Payment, issuance & in-force", "Steps 11–16 · v2.0 adds data-quality & self-service",
        ["Policyholder / Finance", "Policy Admin", "PAS / Self-service"],
        [SwimNode("q1", "Policyholder / Finance", 0, "Initial premium payment", "coverage on payment"),
         SwimNode("q2", "Policy Admin", 1, "Issue policy", "policy number"),
         SwimNode("q3", "Policy Admin", 2, "Dispatch documents", "schedule · cert · PDS"),
         SwimNode("q4", "PAS / Self-service", 3, "Automated data-quality validation", "integrity check", kind="new"),
         SwimNode("q5", "PAS / Self-service", 4, "Self-service endorsements", "STP changes", kind="new")],
        [SwimEdge("q1", "q2"), SwimEdge("q2", "q3"), SwimEdge("q3", "q4"),
         SwimEdge("q4", "q5", dashed=True, kind="new")],
        "v2.0 validates policy data automatically at issuance and lets policyholders self-serve standard mid-term endorsements straight-through."),
    SwimPhase("4", "Claims intake & closure", "Steps 17–18 · lifecycle endpoints",
        ["Policyholder", "Claims", "Policy Admin / Finance"],
        [SwimNode("r1", "Policyholder", 0, "File claim", "portal · hotline"),
         SwimNode("r2", "Claims", 1, "Register & route claim", "SOP-INS-011/012"),
         SwimNode("r3", "Claims", 2, "Settlement approval gate", "POL-CLAIMS-001", kind="decision"),
         SwimNode("r4", "Policy Admin / Finance", 1, "Close policy", "expiry / request / lapse"),
         SwimNode("r5", "Policy Admin / Finance", 2, "Calculate refund & confirm", "SOP-FIN-012", kind="terminal")],
        [SwimEdge("r1", "r2"), SwimEdge("r2", "r3"), SwimEdge("r4", "r5")],
        "Claims intake and policy closure are unchanged in flow but benefit from cleaner, validated lifecycle data."),
]

optimised_doc = OptimisedDoc(
    subtitle="Optimised per Fit-Gap Analysis against the Guidewire PolicyCenter Policy Lifecycle Catalog",
    sections=[
        DocSection("", [
            ("meta", [
                ("Document Reference", "SOP-INS-013"),
                ("Version", "2.0 (Optimised)"),
                ("Effective Date", "01 October 2026"),
                ("Supersedes", "v1.0 dated 01 June 2025"),
                ("Owner", "Policy Administration — Operations"),
                ("Approved By", "Chief Operating Officer"),
                ("Optimisation Reference", "Fit-Gap Report FG-INS-013 dated 18 June 2026"),
                ("Catalog Alignment Score", "90% (up from 67% in v1.0)"),
                ("Classification", "Internal Use Only"),
            ]),
            ("summary", "OPTIMISATION SUMMARY — What changed in v2.0",
             ["This version incorporates 5 remediation actions from Fit-Gap Report FG-INS-013. Alignment to the "
              "Guidewire PolicyCenter lifecycle catalog increased from 67% to 90%. Critical additions: an explicit "
              "KYC/sanctions screening step with continuous monitoring, mandatory e-signature acceptance, automated "
              "underwriting with clause-library document generation, self-service straight-through endorsements, and "
              "automated data-quality validation."],
             ["NEW STEP (green) — step added to close a gap vs the PolicyCenter catalog",
              "ENHANCED (amber) — existing step updated with additional automation or controls"]),
        ]),
        DocSection("1. Purpose", [
            ("para", "This Standard Operating Procedure defines the end-to-end lifecycle process for administering an "
             "insurance policy from application submission to closure. Version 2.0 incorporates optimisations from "
             "fit-gap analysis against the Guidewire PolicyCenter Policy Lifecycle Best-Practice Catalog, achieving "
             "90% alignment (up from 67% in v1.0)."),
        ]),
        DocSection("2. Scope", [
            ("para", "This procedure applies to all personal and commercial lines policies across all channels, "
             "covering new business, mid-term amendments, renewals and closures."),
            ("banner", "new", "Scope extended: KYC/sanctions screening, mandatory e-signature and self-service "
             "endorsements now apply across the policy lifecycle."),
            ("para", "This procedure does NOT cover reinsurance treaty administration (SOP-RE-001), group member-level "
             "enrolment (SOP-INS-006), or claims settlement beyond intake (SOP-INS-011/012)."),
        ]),
        DocSection("3. Authority & Decision Gates", [
            ("table", ["Gate / Decision", "First Authority", "Second Authority"],
             [["Data & coverage approval", "Application Processing Supervisor", "Agent"],
              ["Underwriting decision", "Underwriting Staff", "Model engine (STP)"],
              ["Policy terms approval", "Underwriting Supervisor", "Head of Underwriting"],
              ["Mid-term endorsement", "Policy Administration", "Underwriting (complex)"],
              ["Claim settlement", "Claims Adjuster / Manager", "POL-CLAIMS-001"],
              ["Disputed cancellation", "Compliance", "Legal"]], {}),
        ]),
        DocSection("4. Roles and Responsibilities", [
            ("table", ["Role", "Responsibilities"],
             [["Policyholder / Applicant", "Submits accurate application and documents; e-signs acceptance; pays premium; requests changes."],
              ["Application Processing Staff", "Registers and verifies applications; performs identity and KYC/sanctions screening; routes to underwriting."],
              ["Underwriting Staff", "Owns automated and manual underwriting; sets terms and pricing; approves within authority."],
              ["Policy Administration Staff", "Generates and issues documents; maintains the system of record; processes endorsements and closure."],
              ["Finance", "Processes premium payments; monitors schedules; handles refunds."],
              ["Claims Staff", "Registers and routes claims to the relevant claims SOP."]], {}),
        ]),
        DocSection("5. Screening & Acceptance Controls (New Section — v2.0)", [
            ("banner", "crit", "New section. Required by the PolicyCenter catalog. KYC/sanctions screening and "
             "e-signature acceptance now gate the policy lifecycle."),
            ("table", ["#", "Control", "Responsible", "Output / System", "Timeline"],
             [["S1", "KYC / sanctions screening", "Application Processing / Compliance", "Identity proofed; watchlists screened", "At application"],
              ["S2", "Continuous sanctions monitoring", "Compliance", "Lifecycle watchlist monitoring", "Continuous"],
              ["S3", "Mandatory e-signature acceptance", "Policyholder / Policy Admin", "Auditable DocuSign acceptance", "Pre-issue"]],
             {0: "new", 1: "new", 2: "new"}),
        ]),
        DocSection("6. Process Steps", [
            ("h3", "6.1 Application, Screening & Risk"),
            ("table", ["#", "Step / Activity", "Responsible", "Output / System", "Timeline"],
             [["1", "Policyholder submits application", "Policyholder / Agent", "Application ID; timestamp", "Day 0"],
              ["2", "Collect and verify policyholder data", "Application Processing", "Identity documents verified", "Day 0–1"],
              ["3", "KYC / sanctions screening", "Application Processing / Compliance", "Screened; monitoring enabled", "Day 0–1"],
              ["4", "Verify coverage details and eligibility", "Application Processing", "Checked against guidelines", "Day 0–1"],
              ["5", "Automated underwriting with predictive model", "Underwriting / Model", "STP for rules-clear; refer otherwise", "Day 1"],
              ["6", "Determine the policy price", "Underwriting / Rating Engine", "Premium calculated", "Day 1–2"]],
             {2: "new", 4: "enh"}),
            ("h3", "6.2 Drafting & E-Acceptance"),
            ("table", ["#", "Step / Activity", "Responsible", "Output / System", "Timeline"],
             [["7", "Generate policy from clause library", "Underwriting / Policy Admin", "Configurable templates; Legal exceptions", "Day 2"],
              ["8", "Review and confirm terms", "Underwriting Staff", "Compliance-reviewed final terms", "Day 2"],
              ["9", "Notify policyholder of terms and price", "Policy Administration", "Coverage, premium, deadline", "Day 2"],
              ["10", "Obtain acceptance via mandatory e-signature", "Policyholder / Policy Admin", "Auditable DocuSign acceptance", "Day 2–4"]],
             {0: "enh", 3: "new"}),
            ("h3", "6.3 Payment, Issuance & In-Force"),
            ("table", ["#", "Step / Activity", "Responsible", "Output / System", "Timeline"],
             [["11", "Initial premium payment", "Policyholder / Finance", "Coverage attaches on payment", "Day 4"],
              ["12", "Formally issue the policy", "Policy Administration", "Number and effective date assigned", "Day 4"],
              ["13", "Dispatch policy document", "Policy Administration", "Schedule, cert, PDS within 2 days", "≤2 days"],
              ["14", "Automated data-quality validation", "PAS / System", "Integrity validated at issuance", "Day +0"],
              ["15", "Renewal reminders & payment monitoring", "Policy Administration / PAS", "90/60/30-day alerts; payment tracked", "Ongoing"],
              ["16", "Self-service & STP endorsements", "Policyholder / Policy Admin", "Standard changes self-served", "On request"]],
             {3: "new", 5: "new"}),
            ("h3", "6.4 Claims Intake & Closure"),
            ("table", ["#", "Step / Activity", "Responsible", "Output / System", "Timeline"],
             [["17", "File and manage policyholder claims", "Claims Staff", "Registered in CMS; routed to claims SOP", "On claim"],
              ["18", "Close policy at end of term or on request", "Policy Administration", "Status set; refund per SOP-FIN-012", "≤5 days"]],
             {}),
        ]),
        DocSection("7. Exception Handling", [
            ("h3", "7.1 Application Data Discrepancy"),
            ("numbered", [
                "Application placed on hold; applicant contacted within 2 business days to clarify or resubmit.",
                "Material misrepresentation: Underwriting and Compliance notified; application suspended pending review.",
                "Maximum resolution period: 14 calendar days before withdrawal."]),
            ("h3", "7.2 Applicant Disputes Terms Post-Notification"),
            ("numbered_from", 4, [
                "Agent/Policy Admin liaises with Underwriting on whether terms adjustment is possible within authority.",
                "Maximum two revised offers; further negotiation escalated to Head of Underwriting.",
                "No agreement within 10 business days: application closed as 'Not Taken Up'."]),
            ("h3", "7.3 Screening Hold (New — v2.0)"),
            ("banner", "new", "New exception. A sanctions/PEP match holds the application pending Compliance review before any bind."),
            ("numbered_from", 7, [
                "Screening hit: application held; Compliance dispositions within 1 business day.",
                "Confirmed match: application declined and reported per regulatory obligations."]),
            ("h3", "7.4 Mid-Term Change & Disputed Cancellation"),
            ("numbered_from", 9, [
                "Standard mid-term changes are self-served; complex changes assessed by Underwriting with premium adjustment.",
                "Disputed Meridian-initiated cancellation: closure held 10 business days for internal review.",
                "Regulatory cases escalated to Compliance and Legal; external dispute resolution advised if unresolved."]),
        ]),
        DocSection("8. Systems and Tools", [
            ("table", ["System", "Purpose", "Primary Users"],
             [["Policy Administration System (PAS)", "System of record for the full policy lifecycle", "All roles"],
              ["Rating + Model Engine", "Premium calculation and automated underwriting", "Underwriting, Application Processing"],
              ["KYC / Sanctions Tool", "Identity and watchlist screening and monitoring", "Application Processing, Compliance"],
              ["Billing System (Sapiens)", "Premium scheduling, collection, reconciliation", "Finance, Policy Administration"],
              ["Claims Management System (Majesco)", "Claim registration and routing", "Claims Staff"],
              ["DocuSign", "Mandatory e-signature acceptance and amendments", "Policy Administration, Policyholder"],
              ["Document & Self-Service Platform", "Clause-library generation and self-service endorsements", "Policy Administration, Policyholders"]], {}),
        ]),
        DocSection("9. Key Controls and Audit Points", [
            ("banner", "enh", "Controls expanded in v2.0: KYC/sanctions, e-signature, automated underwriting, "
             "data-quality validation and self-service endorsements."),
            ("bullets", [
                "Screening gate: KYC/sanctions screened at application and monitored across the lifecycle.",
                "E-signature: auditable acceptance of terms before issuance.",
                "Automated underwriting: predictive scoring widens straight-through processing with governance.",
                "Clause library: documents generated from approved, version-controlled templates.",
                "Data integrity: policy data validated automatically at issuance.",
                "Self-service endorsements: standard mid-term changes processed straight-through.",
                "Immutable audit trail: application, screening, acceptance, issuance and change events logged."]),
        ]),
        DocSection("10. Key Performance Indicators", [
            ("table", ["KPI", "v1.0 Target", "v2.0 Target", "Measurement"],
             [["Application-to-issuance", "≤3 business days", "≤2 business days", "Documentation/payment to issuance"],
              ["Straight-through underwriting", "N/A (new)", "≥60%", "Auto-underwritten rate"],
              ["Sanctions screening", "N/A (new)", "100% at application", "Screening log"],
              ["E-signature acceptance", "Verbal allowed", "100% auditable", "E-signature records"],
              ["Policy database accuracy", "100% ≤1 day", "100% validated at issuance", "Data-quality checks"],
              ["Self-service endorsements", "N/A (new)", "≥40% of standard changes", "Self-service vs manual"]], {}),
        ]),
        DocSection("11. Document Control", [
            ("table", ["Version", "Date", "Author", "Summary of Changes"],
             [["1.0", "01 Jun 2025", "A. Tan, Policy Operations", "Initial release — full policy lifecycle SOP consolidating application, issuance, in-force management, claims intake, and closure"],
              ["2.0", "01 Oct 2026", "A. Tan, Policy Operations",
               "OPTIMISED: KYC/sanctions screening & monitoring; mandatory e-signature; automated underwriting & "
               "clause-library generation; self-service straight-through endorsements; automated data-quality "
               "validation; catalog alignment 67% → 90%"]], {}),
        ]),
    ],
)

package = SopPackage(
    meta=meta, phases=phases, steps=steps, authority=authority, swim_phases=swim_phases,
    n_phases=4, n_steps=17, n_roles=7, n_gateways=3,
    fitgap=fitgap,
    opt_phases=opt_phases, opt_steps=opt_steps, opt_swim_phases=opt_swim_phases,
    opt_n_phases=4, opt_n_steps=18, opt_n_gateways=3, opt_fit=90,
    optimised_doc=optimised_doc,
    swim_cover_tags="Application · Underwriting · Issuance · In-force · Claims · Closure",
    hierarchy_cover_sub="Phase breakdown with lifecycle tracks, decision gates, and exception paths",
)
