"""SOP-INS-012 — Property and Casualty Claims (Meridian Insurance Group).

Fit-gap vs the Guidewire ClaimCenter P&C claims best-practice catalog.
"""
from __future__ import annotations

from generator.model import (
    Meta, Phase, Step, AuthorityRow, SwimNode, SwimEdge, SwimPhase,
    FitItem, FitPhaseBar, PhaseScoreCard, CriticalGap, ControlBar,
    Remediation, FitGap, DocSection, OptimisedDoc, SopPackage,
)

CATALOG = "Guidewire ClaimCenter — Property & Casualty Best-Practice Catalog"
CATALOG_SHORT = "Guidewire ClaimCenter"

meta = Meta(
    sop_id="SOP-INS-012", slug="Property_Casualty_Claims",
    title="Property and Casualty Claims", short_title="P&C claims",
    version="3.1", owner="P&C Claims — Claims Operations",
    org="Meridian Insurance Group", catalog=CATALOG, catalog_short=CATALOG_SHORT,
    new_version="4.0", effective_date="01 October 2026",
    supersedes="v3.1 dated 15 January 2025", approved_by="Chief Claims Officer",
    classification="Internal Use Only — Claims Restricted",
)

phases = [
    Phase("1", "FNOL & registration", "Notice, coverage, triage, reserve", "blue",
          "Claimant · Processor · PAS", "Steps 1–4", "4 steps + 1 decision"),
    Phase("2", "Appraisal", "Assign, inspect, report, screen", "green",
          "Processor · Adjuster · Assessor · SIU", "Steps 5–8", "4 steps"),
    Phase("3", "Adjustment & settlement", "Calculate, approve, pay, close", "amber",
          "Adjuster · Claims Manager · Finance", "Steps 9–13", "5 steps + 1 decision"),
    Phase("4", "Subrogation & salvage", "Identify, recover, salvage", "gold",
          "Adjuster · Recovery Analyst · Legal", "Steps 14–16", "3 steps"),
]

steps = [
    Step("1", "1", "FNOL received via phone, portal, app, or mail", "Claims Processor / System",
         "Claim ID assigned; loss date/time, circumstances and contact details recorded", "T+0", "Multi-channel FNOL", kind="trigger"),
    Step("2", "1", "Policy coverage verification", "Claims Processor / PAS",
         "Policy active at loss date; peril covered; deductible and sum insured confirmed; prior claims noted", "T+0", "Coverage check"),
    Step("3", "1", "Initial loss triage and priority assignment", "Claims Processor",
         "Standard / Urgent (fast-track) / Major (Manager) / Fraud Flag (SIU)", "T+0", "Triage routing"),
    Step("4", "1", "Claim registered with reserve and acknowledgement", "Claims Processor",
         "Full record created; reserve estimate set; acknowledgement within 1 business day", "T+1 day", "Reserve at registration"),
    Step("", "1", "", "", "", "", "Triage routing", kind="decision", decision="Loss category?",
         branches=["Standard / Urgent → adjuster queue", "Major → Claims Manager", "Fraud flag → SIU (Sec 6.2)"]),
    Step("5", "2", "Claim assigned to adjuster", "Claims Processor / System",
         "Assignment by type, complexity and workload; adjuster contacts claimant within 2 days", "T+1–2 days", "Assignment SLA"),
    Step("6", "2", "On-site inspection or desktop assessment", "Adjuster / External Assessor",
         "Inspection within 5 days (standard) / 48h (urgent); digital photos for minor losses", "≤5 days", "Inspection SLA"),
    Step("7", "2", "Damage or liability report prepared", "Adjuster / Assessor",
         "Scope of damage; repair estimate or liability assessment; photos attached", "T+3–7 days", "Loss documentation"),
    Step("8", "2", "Fraud screening completed", "Claims System / SIU",
         "Automated fraud score; flagged claims suspended and transferred to SIU within 1 day", "Parallel", "Fraud control", kind="control"),
    Step("9", "3", "Settlement amount calculated", "Adjuster",
         "Loss less deductible; ACV/RCV per policy basis; co-insurance check for property", "T+7–10 days", "Loss settlement basis"),
    Step("10", "3", "Settlement approved within authority", "Adjuster / Claims Manager",
         "Adjuster ≤SGD 50k; Manager 50–250k; CCO >250k", "T+8–10 days", "Authority matrix"),
    Step("11", "3", "Settlement offer communicated to claimant", "Adjuster",
         "Written itemised offer; claimant given 10 business days to accept or dispute", "T+10 days", "Offer & dispute window"),
    Step("12", "3", "Claimant accepts; payment processed", "Adjuster / Finance",
         "Bank transfer or cheque within 5 business days; remittance advice issued", "T+15 days", "Payment SLA"),
    Step("13", "3", "Claim closed and reserves released", "Claims Processor / Finance",
         "Status 'Settled'; reserve adjusted to final paid amount; GL updated in SAP", "T+15 days", "Reserve true-up", kind="complete"),
    Step("14", "4", "Subrogation opportunity identified", "Adjuster / Recovery Analyst",
         "Third-party liability established; recovery potential assessed; assignment of rights obtained", "Post-settlement", "Recovery identification"),
    Step("15", "4", "Subrogation recovery pursued", "Recovery Analyst / Legal",
         "Demand letter to at-fault party/insurer; timeline tracked; Legal for contested recoveries", "Ongoing", "Recovery pursuit"),
    Step("16", "4", "Salvage sold", "Recovery Analyst",
         "Total-loss vehicles and salvageable property sold via approved agent; proceeds reduce loss cost", "Ongoing", "Salvage recovery", kind="complete"),
]

authority = [
    AuthorityRow("Settlement up to SGD 50,000", "Claims Adjuster", "—"),
    AuthorityRow("SGD 50,001–250,000", "Claims Manager", "Adjuster recommendation"),
    AuthorityRow("Above SGD 250,000", "Chief Claims Officer", "Claims Manager"),
    AuthorityRow("Reserve > SGD 100,000", "Claims Manager", "Adjuster"),
    AuthorityRow("Litigation referral", "Claims Manager", "Legal"),
    AuthorityRow("Catastrophe / reinsurance loss", "Chief Claims Officer", "Reinsurance (SOP-RE-001)"),
]

swim_phases = [
    SwimPhase("1", "FNOL & registration", "Steps 1–4 · notice to reserve",
        ["Claimant", "Claims Processor", "PAS / System"],
        [SwimNode("s1", "Claimant", 0, "Submit FNOL", "phone · portal · app"),
         SwimNode("s2", "Claims Processor", 1, "Register & assign Claim ID", "loss details"),
         SwimNode("s3", "Claims Processor", 2, "Coverage verification", "via PAS"),
         SwimNode("s4", "Claims Processor", 3, "Loss triage & priority", "standard / major / fraud", kind="decision"),
         SwimNode("s5", "PAS / System", 4, "Register + reserve + ack", "≤1 day"),
         SwimNode("s6", "PAS / System", 3, "Fraud flag → SIU", "Sec 6.2", kind="exception")],
        [SwimEdge("s1", "s2", dashed=True), SwimEdge("s2", "s3"), SwimEdge("s3", "s4"),
         SwimEdge("s4", "s5"), SwimEdge("s4", "s6", dashed=True, kind="exception", label="fraud")],
        "Multi-channel FNOL is registered with coverage verified and a reserve set at registration; fraud-flagged claims route to SIU."),
    SwimPhase("2", "Appraisal", "Steps 5–8 · assign, inspect, report",
        ["Claims Processor", "Adjuster", "Assessor / SIU"],
        [SwimNode("a1", "Claims Processor", 0, "Assign to adjuster", "by type & workload"),
         SwimNode("a2", "Adjuster", 1, "Inspection / assessment", "≤5 days / 48h urgent"),
         SwimNode("a3", "Assessor / SIU", 2, "External on-site assessment", "major losses"),
         SwimNode("a4", "Adjuster", 3, "Damage / liability report", "scope + estimate"),
         SwimNode("a5", "Assessor / SIU", 1, "Fraud screening", "auto-score · SIU")],
        [SwimEdge("a1", "a2"), SwimEdge("a2", "a3", label="major"), SwimEdge("a3", "a4"),
         SwimEdge("a2", "a4"), SwimEdge("a1", "a5", dashed=True), SwimEdge("a5", "a4", dashed=True)],
        "Claims are assigned and inspected (on-site or desktop) with external assessors for major losses; all claims are fraud-screened in parallel."),
    SwimPhase("3", "Adjustment & settlement", "Steps 9–13 · calculate to close",
        ["Adjuster", "Claims Manager", "Finance"],
        [SwimNode("d1", "Adjuster", 0, "Calculate settlement", "ACV / RCV · deductible"),
         SwimNode("d2", "Claims Manager", 1, "Approve within authority", "matrix", kind="decision"),
         SwimNode("d3", "Adjuster", 2, "Communicate offer", "10-day window"),
         SwimNode("d4", "Finance", 3, "Process payment", "≤5 days"),
         SwimNode("d5", "Finance", 4, "Close & release reserves", "GL updated", kind="terminal"),
         SwimNode("d6", "Claims Manager", 2, "Dispute → review", "Sec 6.1", kind="exception")],
        [SwimEdge("d1", "d2"), SwimEdge("d2", "d3"), SwimEdge("d3", "d4"), SwimEdge("d4", "d5"),
         SwimEdge("d3", "d6", dashed=True, kind="exception", label="dispute")],
        "Settlements are calculated, approved per authority and paid within five days of acceptance; disputes route to the Claims Manager."),
    SwimPhase("4", "Subrogation & salvage", "Steps 14–16 · recover loss cost",
        ["Adjuster", "Recovery Analyst", "Legal"],
        [SwimNode("e1", "Adjuster", 0, "Identify subrogation", "assignment of rights"),
         SwimNode("e2", "Recovery Analyst", 1, "Pursue recovery", "demand letter"),
         SwimNode("e3", "Legal", 2, "Contested recovery", "litigation"),
         SwimNode("e4", "Recovery Analyst", 3, "Sell salvage", "reduces loss cost", kind="terminal")],
        [SwimEdge("e1", "e2"), SwimEdge("e2", "e3", dashed=True, label="contested"), SwimEdge("e2", "e4")],
        "Third-party recoveries and salvage sales reduce ultimate loss cost; contested recoveries are escalated to Legal."),
]

fg_items = [
    FitItem("1", "Multi-channel FNOL", "FIT",
        "Phone, portal, app and mail FNOL with Claim ID aligns with ClaimCenter FNOL intake.",
        "Claims Processor", "GW-CC-FNOL-01", "p1"),
    FitItem("2", "Coverage verification", "FIT",
        "Policy-active, peril, deductible and sum-insured verification via PAS aligns with ClaimCenter coverage check.",
        "Claims Processor / PAS", "GW-CC-FNOL-03", "p1"),
    FitItem("3", "Loss triage & priority", "FIT",
        "Standard/urgent/major/fraud triage aligns with ClaimCenter segmentation and routing.",
        "Claims Processor", "GW-CC-SEG-01", "p1"),
    FitItem("4", "Reserve at registration", "FIT",
        "Initial reserve set when the claim is registered aligns with ClaimCenter reserving discipline.",
        "Claims Processor", "GW-CC-FIN-01", "p1"),
    FitItem("5", "Adjuster assignment", "FIT",
        "Assignment by type, complexity and workload with a 2-day contact SLA aligns with ClaimCenter assignment.",
        "Claims Processor", "GW-CC-ASG-01", "p2"),
    FitItem("6", "AI photo-based damage estimation", "GAP",
        "Digital photos are accepted but estimates are manual. ClaimCenter integrates AI photo-based estimation for "
        "fast, consistent repair costing on motor and property.",
        "Adjuster / System", "GW-CC-EST-02", "p2"),
    FitItem("7", "Inspection & loss documentation", "FIT",
        "Inspection SLAs with scoped damage reports and attached evidence align with ClaimCenter assessment.",
        "Adjuster / Assessor", "GW-CC-ASS-01", "p2"),
    FitItem("8", "Fraud screening & analytics", "PARTIAL",
        "Automated fraud scoring and SIU referral are present, but without network/link analytics across claims and "
        "parties recommended by the catalog.",
        "Claims System / SIU", "GW-CC-SIU-01", "p2"),
    FitItem("9", "Settlement calculation", "FIT",
        "ACV/RCV with deductible and co-insurance checks aligns with ClaimCenter settlement evaluation.",
        "Adjuster", "GW-CC-STL-01", "p3"),
    FitItem("10", "Authority & approval", "FIT",
        "Tiered settlement authority (adjuster/manager/CCO) aligns with ClaimCenter authority management.",
        "Adjuster / Claims Manager", "GW-CC-AUT-01", "p3"),
    FitItem("11", "Touchless / STP settlement", "GAP",
        "Even simple, low-value claims follow the full adjuster path. ClaimCenter offers straight-through, "
        "self-service settlement for clear minor claims, cutting cycle time and cost.",
        "Claims System", "GW-CC-STP-01", "p3"),
    FitItem("12", "Managed-repair vendor network", "PARTIAL",
        "Repairs are authorised ad hoc; there is no preferred/managed-repair network with direct-repair and "
        "guarantees as the catalog recommends, raising indemnity cost.",
        "Adjuster", "GW-CC-VEN-01", "p3"),
    FitItem("13", "Predictive reserving & analytics", "PARTIAL",
        "Reserves are set on adjuster judgement with a variance KPI. ClaimCenter uses predictive reserving and "
        "large-loss/litigation propensity analytics for accuracy and early escalation.",
        "Adjuster / Claims Manager", "GW-CC-ANL-01", "p3"),
    FitItem("14", "Payment & closure", "FIT",
        "Payment within 5 days, closure and reserve release with GL update align with ClaimCenter financials.",
        "Adjuster / Finance", "GW-CC-FIN-03", "p3"),
    FitItem("15", "Subrogation & recovery", "FIT",
        "Subrogation identification, demand and Legal handling align with ClaimCenter recovery management.",
        "Recovery Analyst / Legal", "GW-CC-REC-01", "p4"),
    FitItem("16", "Salvage management", "FIT",
        "Salvage sale via approved agents with proceeds reducing loss cost aligns with ClaimCenter salvage.",
        "Recovery Analyst", "GW-CC-SAL-01", "p4"),
]

fitgap = FitGap(
    overall_fit=74, partial_pct=14, fits=12, gaps=2, partials=2,
    steps_analysed=16, phases_count=4,
    summary_line="Overall alignment of SOP-INS-012 against the Guidewire ClaimCenter P&C catalog",
    metrics=[
        ("Steps analysed", "16 steps across 4 phases"),
        ("Fits confirmed", "12 steps aligned to catalog"),
        ("Gaps identified", "2 steps — remediation required"),
        ("Partial fits", "2 steps — enhancement recommended"),
        ("Highest risk area", "No AI estimation / touchless STP"),
        ("Indemnity gap", "No managed-repair network"),
        ("Ref standard", "Guidewire ClaimCenter P&C Catalog"),
    ],
    phase_bars=[
        FitPhaseBar("Phase 1", "FNOL", 88, ""),
        FitPhaseBar("Phase 2", "Appraisal", 68, ""),
        FitPhaseBar("Phase 3", "Settlement", 70, ""),
        FitPhaseBar("Phase 4", "Recovery", 82, ""),
    ],
    phase_cards=[
        PhaseScoreCard("Phase 1", 88, "FNOL & registration"),
        PhaseScoreCard("Phase 2", 68, "Appraisal"),
        PhaseScoreCard("Phase 3", 70, "Adjustment & settlement"),
        PhaseScoreCard("Phase 4", 82, "Subrogation & salvage"),
    ],
    detail_slides=[
        ("Phase 1 — FNOL & registration", "Steps 1–4 vs Guidewire ClaimCenter P&C catalog", ["p1"]),
        ("Phase 2 — Appraisal", "Steps 5–8 vs Guidewire ClaimCenter P&C catalog", ["p2"]),
        ("Phase 3 — Adjustment & settlement", "Steps 9–14 vs Guidewire ClaimCenter P&C catalog", ["p3"]),
        ("Phase 4 — Subrogation & salvage", "Steps 15–16 vs Guidewire ClaimCenter P&C catalog", ["p4"]),
    ],
    items=fg_items,
    groups=[("p1", "PHASE 1 — FNOL & REGISTRATION"),
            ("p2", "PHASE 2 — APPRAISAL"),
            ("p3", "PHASE 3 — ADJUSTMENT & SETTLEMENT"),
            ("p4", "PHASE 4 — SUBROGATION & SALVAGE")],
    critical_missing=[
        CriticalGap("AI photo-based damage estimation",
            "Digital photos are accepted but estimates are manual. The catalog integrates AI photo-based estimating "
            "for fast, consistent repair costing and lower leakage on motor and property."),
        CriticalGap("Touchless / straight-through settlement",
            "Simple, low-value claims still follow the full adjuster path. The catalog provides straight-through, "
            "self-service settlement for clear minor claims, cutting cycle time and cost."),
        CriticalGap("Managed-repair vendor network",
            "Repairs are authorised ad hoc with no preferred/managed-repair network, direct-repair or guarantees, "
            "raising indemnity cost and lengthening cycle time."),
        CriticalGap("Predictive reserving & loss analytics",
            "Reserves rely on adjuster judgement; the catalog uses predictive reserving and large-loss/litigation "
            "propensity analytics for accuracy and early escalation."),
    ],
    radar=[("FNOL", 90), ("Coverage", 85), ("Estimation", 50), ("Fraud / SIU", 68),
           ("Settlement", 72), ("Managed repair", 45), ("Recovery", 84)],
    control_bars=[
        ControlBar("FNOL & registration", 88, "Multi-channel FNOL with reserve at registration"),
        ControlBar("Coverage verification", 85, "Active-policy, peril and deductible checks"),
        ControlBar("Damage estimation", 50, "Manual estimating; no AI photo estimation"),
        ControlBar("Fraud & SIU", 68, "Scoring and SIU; no network/link analytics"),
        ControlBar("Touchless settlement", 45, "Full adjuster path even for minor claims"),
        ControlBar("Managed repair", 45, "Ad-hoc repair authorisation; no network"),
        ControlBar("Recovery & salvage", 84, "Subrogation and salvage well established"),
    ],
    remediations=[
        Remediation(1, "Integrate AI photo-based damage estimation",
            "Add AI estimating on motor and property photos for fast, consistent repair costing and reduced leakage. "
            "Effort: 6 weeks (vendor integration).", "High"),
        Remediation(2, "Enable touchless / STP settlement for minor claims",
            "Auto-adjudicate clear, low-value claims with self-service settlement, routing only exceptions to "
            "adjusters. Effort: 6 weeks.", "High"),
        Remediation(3, "Stand up a managed-repair vendor network",
            "Establish a preferred/managed-repair network with direct-repair, agreed rates and guarantees to control "
            "indemnity and cycle time. Effort: 8 weeks.", "High"),
        Remediation(4, "Add predictive reserving & loss analytics",
            "Introduce predictive reserving and large-loss/litigation propensity analytics for accurate reserves and "
            "early escalation. Effort: 5 weeks.", "Medium"),
        Remediation(5, "Add claimant self-service tracking & SIU analytics",
            "Provide a claimant status-tracking portal and extend fraud screening with network/link analytics. "
            "Effort: 5 weeks.", "Medium"),
    ],
    risk_impact=[("AI estimation", 80), ("Touchless settlement", 78), ("Managed repair", 75),
                 ("Predictive reserving", 65), ("SIU analytics", 55), ("Self-service tracking", 50)],
    projected_fit=93,
)

opt_phases = [
    Phase("1", "FNOL, triage & reserving", "Notice, coverage, triage, reserve", "blue",
          "Claimant · Processor · PAS", "Steps 1–4", "4 steps + 1 decision"),
    Phase("2", "Appraisal & estimation", "Assign, AI estimate, inspect, screen", "green",
          "Processor · Adjuster · Assessor · SIU", "Steps 5–9", "5 steps"),
    Phase("3", "Settlement & repair", "STP, managed repair, approve, pay", "amber",
          "Adjuster · Claims Manager · Finance", "Steps 10–14", "5 steps + 1 decision"),
    Phase("4", "Subrogation & salvage", "Identify, recover, salvage", "gold",
          "Adjuster · Recovery Analyst · Legal", "Steps 15–17", "3 steps"),
]

opt_steps = [
    Step("1", "1", "FNOL received (multi-channel)", "Claims Processor / System",
         "Claim ID; loss details and contact captured", "T+0", "Standard", kind="trigger"),
    Step("2", "1", "Policy coverage verification", "Claims Processor / PAS",
         "Active policy, peril, deductible and sum insured confirmed", "T+0", "Standard"),
    Step("3", "1", "Loss triage with predictive segmentation", "Claims Processor / Model",
         "Triage augmented by large-loss/litigation propensity scoring", "T+0", "ENHANCED (v4.0)"),
    Step("4", "1", "Register with predictive reserve & acknowledgement", "Claims Processor / Model",
         "Predictive reserve set; acknowledgement within 1 business day", "T+1 day",
         "ENHANCED (v4.0) — reserve accuracy"),
    Step("", "1", "", "", "", "", "Triage routing", kind="decision", decision="Loss category?",
         branches=["Minor & clear → touchless settlement", "Standard/major → adjuster", "Fraud → SIU"]),
    Step("5", "2", "Claim assigned (or routed to STP)", "Claims Processor / System",
         "Clear minor claims routed to straight-through settlement; others assigned to adjuster", "T+1–2 days",
         "ENHANCED (v4.0)"),
    Step("6", "2", "AI photo-based damage estimation", "Adjuster / AI Estimator",
         "AI estimate from claimant/assessor photos for motor and property", "T+1–3 days",
         "NEW (v4.0) — fast, consistent costing"),
    Step("7", "2", "Inspection or desktop assessment", "Adjuster / External Assessor",
         "On-site for major losses; AI/desktop for minor; SLAs unchanged", "≤5 days", "Standard"),
    Step("8", "2", "Damage / liability report prepared", "Adjuster / Assessor",
         "Scope, estimate and evidence attached to the claim file", "T+3–7 days", "Standard"),
    Step("9", "2", "Fraud screening with network analytics", "Claims System / SIU",
         "Fraud scoring plus network/link analytics across claims and parties", "Parallel",
         "ENHANCED (v4.0)"),
    Step("10", "3", "Touchless settlement for clear minor claims", "Claims System",
         "Straight-through self-service settlement for clear, low-value claims", "Same day",
         "NEW (v4.0) — cycle-time reduction"),
    Step("11", "3", "Managed-repair authorisation (network)", "Adjuster / Repair Network",
         "Repairs directed to a managed network at agreed rates with guarantees", "T+5–8 days",
         "NEW (v4.0) — indemnity control"),
    Step("12", "3", "Settlement approved within authority", "Adjuster / Claims Manager",
         "Adjuster ≤SGD 50k; Manager 50–250k; CCO >250k", "T+8–10 days", "Standard"),
    Step("13", "3", "Offer communicated and accepted; payment", "Adjuster / Finance",
         "Itemised offer; payment within 5 business days of acceptance", "T+15 days", "Standard"),
    Step("14", "3", "Claim closed and reserves released", "Claims Processor / Finance",
         "Status 'Settled'; reserve trued-up; GL updated", "T+15 days", "Standard", kind="complete"),
    Step("15", "4", "Subrogation identified (analytics-assisted)", "Adjuster / Recovery Analyst",
         "Recovery opportunities surfaced by analytics; assignment of rights obtained", "Post-settlement",
         "ENHANCED (v4.0)"),
    Step("16", "4", "Subrogation recovery pursued", "Recovery Analyst / Legal",
         "Demand to at-fault party/insurer; Legal for contested recoveries", "Ongoing", "Standard"),
    Step("17", "4", "Salvage sold", "Recovery Analyst",
         "Salvage sold via approved agents; proceeds reduce loss cost", "Ongoing", "Standard", kind="complete"),
]

opt_swim_phases = [
    SwimPhase("1", "FNOL, triage & reserving", "Steps 1–4 · v4.0 adds predictive reserving",
        ["Claimant", "Claims Processor", "PAS / Model"],
        [SwimNode("o1", "Claimant", 0, "Submit FNOL", "phone · portal · app"),
         SwimNode("o2", "Claims Processor", 1, "Register & assign Claim ID", "loss details"),
         SwimNode("o3", "Claims Processor", 2, "Coverage verification", "via PAS"),
         SwimNode("o4", "PAS / Model", 3, "Predictive triage", "propensity score", kind="enhanced"),
         SwimNode("o5", "PAS / Model", 4, "Predictive reserve + ack", "≤1 day", kind="enhanced")],
        [SwimEdge("o1", "o2", dashed=True), SwimEdge("o2", "o3"), SwimEdge("o3", "o4"),
         SwimEdge("o4", "o5")],
        "v4.0 augments triage and reserving with predictive analytics for accuracy and early escalation."),
    SwimPhase("2", "Appraisal & estimation", "Steps 5–9 · v4.0 adds AI estimation",
        ["Claims Processor", "Adjuster / AI", "Assessor / SIU"],
        [SwimNode("p1", "Claims Processor", 0, "Assign or route to STP", "minor → STP", kind="enhanced"),
         SwimNode("p2", "Adjuster / AI", 1, "AI photo-based estimation", "motor · property", kind="new"),
         SwimNode("p3", "Assessor / SIU", 2, "Inspection (major losses)", "on-site"),
         SwimNode("p4", "Adjuster / AI", 3, "Damage / liability report", "scope + estimate"),
         SwimNode("p5", "Assessor / SIU", 1, "Fraud + network analytics", "link analysis", kind="enhanced")],
        [SwimEdge("p1", "p2"), SwimEdge("p2", "p3", label="major"), SwimEdge("p3", "p4"),
         SwimEdge("p2", "p4"), SwimEdge("p1", "p5", dashed=True)],
        "v4.0 adds AI photo-based estimation for fast costing and extends fraud screening with network/link analytics."),
    SwimPhase("3", "Settlement & repair", "Steps 10–14 · v4.0 adds STP & managed repair",
        ["Adjuster", "Claims Manager / Network", "Finance"],
        [SwimNode("q1", "Claims Manager / Network", 0, "Touchless settlement (minor)", "self-service", kind="new"),
         SwimNode("q2", "Adjuster", 0, "Calculate settlement", "ACV / RCV"),
         SwimNode("q3", "Claims Manager / Network", 1, "Managed-repair authorisation", "agreed rates", kind="new"),
         SwimNode("q4", "Claims Manager / Network", 2, "Approve within authority", "matrix", kind="decision"),
         SwimNode("q5", "Finance", 3, "Pay & close; release reserves", "≤5 days", kind="terminal")],
        [SwimEdge("q2", "q3"), SwimEdge("q3", "q4"), SwimEdge("q4", "q5"),
         SwimEdge("q1", "q5", dashed=True, kind="new", label="STP")],
        "v4.0 settles clear minor claims straight-through and directs repairs to a managed network at agreed rates."),
    SwimPhase("4", "Subrogation & salvage", "Steps 15–17 · analytics-assisted recovery",
        ["Adjuster", "Recovery Analyst", "Legal"],
        [SwimNode("r1", "Adjuster", 0, "Identify subrogation (analytics)", "opportunities surfaced", kind="enhanced"),
         SwimNode("r2", "Recovery Analyst", 1, "Pursue recovery", "demand letter"),
         SwimNode("r3", "Legal", 2, "Contested recovery", "litigation"),
         SwimNode("r4", "Recovery Analyst", 3, "Sell salvage", "reduces loss cost", kind="terminal")],
        [SwimEdge("r1", "r2"), SwimEdge("r2", "r3", dashed=True, label="contested"), SwimEdge("r2", "r4")],
        "v4.0 surfaces subrogation opportunities through analytics; recovery and salvage continue to reduce loss cost."),
]

optimised_doc = OptimisedDoc(
    subtitle="Optimised per Fit-Gap Analysis against the Guidewire ClaimCenter P&C Catalog",
    sections=[
        DocSection("", [
            ("meta", [
                ("Document Reference", "SOP-INS-012"),
                ("Version", "4.0 (Optimised)"),
                ("Effective Date", "01 October 2026"),
                ("Supersedes", "v3.1 dated 15 January 2025"),
                ("Owner", "P&C Claims — Claims Operations"),
                ("Approved By", "Chief Claims Officer"),
                ("Optimisation Reference", "Fit-Gap Report FG-INS-012 dated 18 June 2026"),
                ("Catalog Alignment Score", "93% (up from 74% in v3.1)"),
                ("Classification", "Internal Use Only — Claims Restricted"),
            ]),
            ("summary", "OPTIMISATION SUMMARY — What changed in v4.0",
             ["This version incorporates 5 remediation actions from Fit-Gap Report FG-INS-012. Alignment to the "
              "Guidewire ClaimCenter P&C catalog increased from 74% to 93%. Critical additions: AI photo-based damage "
              "estimation, touchless/straight-through settlement for minor claims, a managed-repair vendor network, "
              "predictive reserving and loss analytics, and SIU network analytics."],
             ["NEW STEP (green) — step added to close a gap vs the ClaimCenter catalog",
              "ENHANCED (amber) — existing step updated with additional automation or controls"]),
        ]),
        DocSection("1. Purpose", [
            ("para", "This Standard Operating Procedure defines the end-to-end process for receiving, triaging, "
             "appraising, adjusting and settling property and casualty claims, including subrogation and salvage. "
             "Version 4.0 incorporates optimisations from fit-gap analysis against the Guidewire ClaimCenter P&C "
             "Best-Practice Catalog, achieving 93% alignment (up from 74% in v3.1)."),
        ]),
        DocSection("2. Scope", [
            ("para", "This procedure applies to all personal and commercial property damage claims, casualty and "
             "third-party liability claims, FNOL across channels, and subrogation and salvage recovery."),
            ("banner", "new", "Scope extended: AI estimation, touchless settlement and managed-repair now apply to "
             "eligible motor and property claims."),
            ("para", "This procedure does NOT cover medical claims (SOP-INS-011), life claims (SOP-INS-013), or "
             "reinsurance claim notifications (SOP-RE-001)."),
        ]),
        DocSection("3. Settlement Authority Matrix", [
            ("table", ["Settlement / Action", "First Authority", "Second Authority"],
             [["Settlement up to SGD 50,000", "Claims Adjuster", "—"],
              ["SGD 50,001–250,000", "Claims Manager", "Adjuster recommendation"],
              ["Above SGD 250,000", "Chief Claims Officer", "Claims Manager"],
              ["Reserve > SGD 100,000", "Claims Manager", "Adjuster"],
              ["Litigation referral", "Claims Manager", "Legal"],
              ["Catastrophe / reinsurance loss", "Chief Claims Officer", "Reinsurance (SOP-RE-001)"]], {}),
        ]),
        DocSection("4. Roles and Responsibilities", [
            ("table", ["Role", "Responsibilities"],
             [["Claims Processor", "Registers FNOL; verifies coverage; triages; assigns; closes the file."],
              ["Claims Adjuster", "Assesses damage/liability; uses AI estimation; directs managed repair; settles within authority; identifies subrogation."],
              ["Claims Manager", "Approves above adjuster authority; oversees predictive reserving; manages litigation referrals."],
              ["External Assessor", "On-site assessment for major losses; independent estimates."],
              ["Fraud & SIU", "Investigates flagged claims; runs network/link analytics; recommends action."],
              ["Recovery Analyst", "Pursues subrogation (analytics-assisted) and salvage recovery."]], {}),
        ]),
        DocSection("5. Estimation, Settlement & Repair Controls (New Section — v4.0)", [
            ("banner", "crit", "New section. Required by the ClaimCenter catalog. AI estimation, touchless settlement "
             "and managed-repair now govern eligible motor and property claims."),
            ("table", ["#", "Control", "Responsible", "Output / System", "Timeline"],
             [["A1", "AI photo-based damage estimation", "Adjuster / AI", "Consistent estimate from photos", "T+1–3 days"],
              ["A2", "Touchless / STP settlement", "Claims System", "Self-service settlement for clear minor claims", "Same day"],
              ["A3", "Managed-repair network authorisation", "Adjuster / Network", "Direct-repair at agreed rates with guarantee", "T+5–8 days"],
              ["A4", "Predictive reserving & analytics", "Claims Manager", "Reserve and large-loss propensity from models", "At registration"]],
             {0: "new", 1: "new", 2: "new", 3: "enh"}),
        ]),
        DocSection("6. Process Steps", [
            ("h3", "6.1 FNOL, Triage & Reserving"),
            ("table", ["#", "Step / Activity", "Responsible", "Output / System", "Timeline"],
             [["1", "FNOL received (multi-channel)", "Claims Processor", "Claim ID; loss details", "T+0"],
              ["2", "Policy coverage verification", "Claims Processor / PAS", "Peril, deductible, sum insured", "T+0"],
              ["3", "Loss triage with predictive segmentation", "Claims Processor / Model", "Propensity-scored triage", "T+0"],
              ["4", "Register with predictive reserve & acknowledgement", "Claims Processor / Model", "Reserve; ack ≤1 day", "T+1 day"]],
             {2: "enh", 3: "enh"}),
            ("h3", "6.2 Appraisal & Estimation"),
            ("table", ["#", "Step / Activity", "Responsible", "Output / System", "Timeline"],
             [["5", "Claim assigned (or routed to STP)", "Claims Processor", "Minor clear → STP; others assigned", "T+1–2 days"],
              ["6", "AI photo-based damage estimation", "Adjuster / AI", "Estimate from photos", "T+1–3 days"],
              ["7", "Inspection or desktop assessment", "Adjuster / Assessor", "On-site for major; AI/desktop for minor", "≤5 days"],
              ["8", "Damage / liability report prepared", "Adjuster / Assessor", "Scope, estimate, evidence", "T+3–7 days"],
              ["9", "Fraud screening with network analytics", "Claims System / SIU", "Scoring + link analytics", "Parallel"]],
             {0: "enh", 1: "new", 4: "enh"}),
            ("h3", "6.3 Settlement & Repair"),
            ("table", ["#", "Step / Activity", "Responsible", "Output / System", "Timeline"],
             [["10", "Touchless settlement for clear minor claims", "Claims System", "Self-service settlement", "Same day"],
              ["11", "Managed-repair authorisation (network)", "Adjuster / Network", "Direct-repair at agreed rates", "T+5–8 days"],
              ["12", "Settlement approved within authority", "Adjuster / Claims Manager", "Per authority matrix", "T+8–10 days"],
              ["13", "Offer communicated and accepted; payment", "Adjuster / Finance", "Payment within 5 days", "T+15 days"],
              ["14", "Claim closed and reserves released", "Claims Processor / Finance", "Reserve trued-up; GL", "T+15 days"]],
             {0: "new", 1: "new"}),
            ("h3", "6.4 Subrogation & Salvage"),
            ("table", ["#", "Step / Activity", "Responsible", "Output / System", "Timeline"],
             [["15", "Subrogation identified (analytics-assisted)", "Adjuster / Recovery Analyst", "Opportunities surfaced", "Post-settlement"],
              ["16", "Subrogation recovery pursued", "Recovery Analyst / Legal", "Demand; litigation if contested", "Ongoing"],
              ["17", "Salvage sold", "Recovery Analyst", "Proceeds reduce loss cost", "Ongoing"]],
             {0: "enh"}),
        ]),
        DocSection("7. Exception Handling", [
            ("h3", "7.1 Disputed Settlement"),
            ("numbered", [
                "Claimant disputes in writing within 10 business days; dispute logged in the Claims System.",
                "Claims Manager reviews within 5 business days; revised offer or maintained position communicated in writing.",
                "Unresolved after 30 days: claimant advised of external dispute resolution (FIDREC / MAS scheme)."]),
            ("h3", "7.2 Suspected Fraud (Enhanced — v4.0)"),
            ("banner", "enh", "Network/link analytics now strengthen fraud detection across related claims and parties."),
            ("numbered_from", 4, [
                "SIU takes custody of the claim; settlement is suspended.",
                "Investigation completed within 20 business days; Claims Manager decides to reject, settle or refer.",
                "Rejected fraud claims logged and submitted to the industry fraud database."]),
            ("h3", "7.3 Total Loss (Motor)"),
            ("numbered_from", 7, [
                "Total loss declared when repair cost exceeds 75% of pre-accident market value.",
                "Market valuation obtained from an approved independent valuer; settlement on market value less salvage.",
                "Finance encumbrance checked; payment directed to the financier first where applicable."]),
            ("h3", "7.4 Major or Catastrophe Loss"),
            ("numbered_from", 10, [
                "Claims Manager notified immediately; CCO briefed for losses above SGD 250,000.",
                "External loss adjusters deployed; a dedicated major-loss team assigned.",
                "Reinsurance notification triggered per SOP-RE-001 above treaty retention."]),
        ]),
        DocSection("8. Systems and Tools", [
            ("table", ["System", "Purpose", "Primary Users"],
             [["Claims Management System (Majesco)", "FNOL, workflow, assessment, settlement, reserves", "All Claims roles"],
              ["Policy Administration System (PAS)", "Coverage, terms, prior-claims history", "Claims Processor, Adjuster"],
              ["AI Estimation Engine", "Photo-based damage estimation", "Adjuster"],
              ["Managed-Repair Network", "Direct-repair authorisation and tracking", "Adjuster, Repairers"],
              ["SAP S/4HANA", "Payment, reserve GL, subrogation accounting", "Finance, Claims Manager"],
              ["Fraud Detection & Analytics", "Fraud scoring and network/link analytics", "Automated, SIU"],
              ["Assessor & Salvage Platforms", "Assessor reports and salvage sale", "External Assessor, Recovery Analyst"]], {}),
        ]),
        DocSection("9. Key Controls and Audit Points", [
            ("banner", "enh", "Controls expanded in v4.0: AI estimation, touchless settlement, managed-repair, "
             "predictive reserving and SIU network analytics."),
            ("bullets", [
                "Reserve at registration: predictive reserve set when the claim is created.",
                "AI estimation: consistent photo-based repair costing reduces leakage.",
                "Touchless settlement: clear minor claims settled straight-through with self-service.",
                "Managed repair: indemnity controlled via a network with agreed rates and guarantees.",
                "Fraud analytics: scoring plus network/link analysis across claims and parties.",
                "Segregation of duties: assessor ≠ settlement approver ≠ payment.",
                "Immutable audit trail: FNOL, estimate, settlement, payment and recovery events logged."]),
        ]),
        DocSection("10. Key Performance Indicators", [
            ("table", ["KPI", "v3.1 Target", "v4.0 Target", "Measurement"],
             [["FNOL acknowledgement", "100% ≤1 day", "100% ≤1 day", "Ack within 1 business day"],
              ["Straight-through settlement", "N/A (new)", "≥30% of minor claims", "Touchless settlement rate"],
              ["Claims cycle time", "80% ≤15 days", "80% ≤10 days", "Receipt to settlement"],
              ["Reserve adequacy variance", "<10%", "<6%", "Initial vs final reserve"],
              ["Subrogation recovery", "≥65%", "≥72%", "Recovered / identified"],
              ["Managed-repair adoption", "N/A (new)", "≥50% of repairs", "Network vs ad-hoc repairs"]], {}),
        ]),
        DocSection("11. Document Control", [
            ("table", ["Version", "Date", "Author", "Summary of Changes"],
             [["3.1", "15 Jan 2025", "E. Okafor, Claims Manager", "Updated SGD authority thresholds; added total loss motor protocol; aligned to reinsurance notification SOP"],
              ["4.0", "01 Oct 2026", "E. Okafor, Claims Manager",
               "OPTIMISED: AI photo-based estimation; touchless/STP settlement; managed-repair network; predictive "
               "reserving & analytics; SIU network analytics; catalog alignment 74% → 93%"]], {}),
        ]),
    ],
)

package = SopPackage(
    meta=meta, phases=phases, steps=steps, authority=authority, swim_phases=swim_phases,
    n_phases=4, n_steps=16, n_roles=6, n_gateways=3,
    fitgap=fitgap,
    opt_phases=opt_phases, opt_steps=opt_steps, opt_swim_phases=opt_swim_phases,
    opt_n_phases=4, opt_n_steps=17, opt_n_gateways=3, opt_fit=93,
    optimised_doc=optimised_doc,
    swim_cover_tags="FNOL · Appraisal · Settlement · Subrogation · Exception handling",
    hierarchy_cover_sub="Phase breakdown with claims tracks, settlement authority, and exception paths",
)
